In [1]:
! python3 -m pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([11, 44, 88])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim

1

In [6]:
arr.shape

(3,)

In [7]:
arr[0]

11

In [15]:
arr = np.array([[11, 44, 88], [22, 33, 99]])

In [16]:
arr

array([[11, 44, 88],
       [22, 33, 99]])

In [17]:
arr.ndim

2

In [11]:
arr.shape

(2, 3)

In [19]:
arr = np.array([[11, 44, 88], [22, 33]])

In [20]:
arr.shape

(2,)

In [21]:
arr

array([list([11, 44, 88]), list([22, 33])], dtype=object)

In [22]:
type(arr[0])

list

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(10, 30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [40]:
a = np.arange(10, 30, 2, dtype=int)

In [41]:
a.dtype

dtype('int64')

In [42]:
np.arange(10, 30, 2, dtype=np.float32)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28.], dtype=float32)

In [44]:
twod = np.arange(100).reshape(10, 10)

In [45]:
twod

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
twod.T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [48]:
print(twod.max(), twod.min(), twod.mean())

99 0 49.5


In [49]:
threed = np.arange(24).reshape(4, 3, 2)

In [52]:
threed[0, 1]

array([0, 1])

In [55]:
threed[:, 0, 0], threed[:, 0, 1]

(array([ 0,  6, 12, 18]), array([ 1,  7, 13, 19]))

In [56]:
threed[:, 1, 0], threed[:, 1, 1]

(array([ 2,  8, 14, 20]), array([ 3,  9, 15, 21]))

In [57]:
threed[:, 2, 0], threed[:, 2, 1]

(array([ 4, 10, 16, 22]), array([ 5, 11, 17, 23]))

In [54]:
np.sum(threed, axis=0)

array([[36, 40],
       [44, 48],
       [52, 56]])

In [62]:
threed[1, :, 1]

array([ 7,  9, 11])

In [59]:
np.sum(threed, axis=1)

array([[ 6,  9],
       [24, 27],
       [42, 45],
       [60, 63]])

In [63]:
threed

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [65]:
threed[:2, :2, :2]

array([[[0, 1],
        [2, 3]],

       [[6, 7],
        [8, 9]]])

In [67]:
np.zeros([3, 4, 5], dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [68]:
np.ones([3, 4, 5], dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [71]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [74]:
th = np.random.randint(0, 10, 24).reshape(4, 3, 2)

In [75]:
th

array([[[9, 0],
        [9, 6],
        [2, 5]],

       [[0, 2],
        [2, 1],
        [4, 8]],

       [[3, 0],
        [7, 1],
        [3, 3]],

       [[0, 2],
        [4, 5],
        [8, 6]]])

In [77]:
th.reshape(4, 6)

array([[9, 0, 9, 6, 2, 5],
       [0, 2, 2, 1, 4, 8],
       [3, 0, 7, 1, 3, 3],
       [0, 2, 4, 5, 8, 6]])

In [78]:
th.reshape(8, 3)

array([[9, 0, 9],
       [6, 2, 5],
       [0, 2, 2],
       [1, 4, 8],
       [3, 0, 7],
       [1, 3, 3],
       [0, 2, 4],
       [5, 8, 6]])