In [1]:
import numpy as np

In [8]:
arr = np.random.randn(1000) 

In [9]:
arr.std()

0.9762986405716182

In [10]:
arr.mean()

-0.017124171253781847

In [15]:
arr = 5 * np.random.randn(1000)  + 10

In [16]:
arr.std(), arr.mean()

(4.965390934842708, 10.137062315790578)

In [25]:
np.random.randn(10)

array([ 1.4965111 , -0.75165231,  0.31113791, -0.94907557,  0.64459261,
        1.04566358, -0.17435636,  0.75187909,  0.0124972 , -0.60956695])

In [22]:
np.mean(a)

0.02033600203940348

In [61]:
np.random.seed(1708)

In [62]:
np.random.randn(10)

array([-0.29265723,  1.21338941, -1.89196982, -0.03599744,  1.47741621,
       -0.09463627, -1.29661244, -0.12719825, -1.4953844 , -0.8030849 ])

In [63]:
np.random.randn(10)

array([ 0.42764838, -0.48548549, -0.13787311,  0.31190334, -0.46226355,
       -0.62645685, -1.27082471,  1.40864632, -1.45878866,  1.35075277])

In [64]:
np.random.randint(0, 10, 10)

array([2, 1, 1, 4, 0, 9, 5, 4, 2, 8])

In [65]:
np.random.randint(0, 10, 10)

array([5, 9, 5, 7, 4, 1, 2, 5, 7, 3])

In [66]:
np.random.random_sample(10)

array([0.84774718, 0.88378135, 0.4235481 , 0.51883739, 0.22394117,
       0.48097396, 0.9111777 , 0.59894356, 0.06752586, 0.70389114])