In [27]:
import gym
import numpy as np
env = gym.make('CartPole-v0')
# env.reset()
# for _ in range(1000):
#     env.render()
# #     env.step(env.action_space.sample()) # take a random action
# env.close()

In [15]:
dir(env)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_elapsed_steps',
 '_max_episode_steps',
 'action_space',
 'class_name',
 'close',
 'compute_reward',
 'env',
 'metadata',
 'observation_space',
 'render',
 'reset',
 'reward_range',
 'seed',
 'spec',
 'step',
 'unwrapped']

In [41]:
env._elapsed_steps

6

In [11]:
env.reset()

array([ 0.0210375 , -0.00454786,  0.01400089, -0.0214043 ])

In [14]:
env.action_space

Discrete(2)

In [37]:
env.unwrapped.state = np.array([ 0.01694919, -0.39518071,  0.01908606,  0.57259569])

In [40]:
env.step(0)

(array([-0.00276572, -0.78608869,  0.04796257,  1.17335527]), 1.0, False, {})

In [42]:
env.reset()

array([ 0.04827976,  0.03542194,  0.03964309, -0.02801276])

In [45]:
env._elapsed_steps

9

In [44]:
done = False

while(not done):
    state, reward, done, info = env.step(0)
    i+=1

In [46]:
i

9